name: Build, push and deploy

on:
  push:
  workflow_dispatch:

env:
  DEPLOYMENT_NAME: ${{ vars.TEAMNAME }}
  DEPLOYMENT_TOKEN: ${{ secrets.TOKEN }}
  NAMESPACE: ${{ vars.NAMESPACE }}

jobs:
  build:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    name: Build app
    steps:
      - name: Checkout the code
        uses: actions/checkout@master

      - name: Prepare repository name
        run: |
          echo IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/${{ env.IMAGE_REPOSITORY }}:latest

      - name: 'Deploy'
#        if: github.ref == 'refs/heads/main'
        uses: 'vimeda/helm@v1'
        with:
          release: '${{ env.DEPLOYMENT_NAME }}'
          namespace: '${{ env.NAMESPACE }}'
          chart: 'charts/player'
          token: '${{ github.token }}'
          values: |
            ingress.hosts[0].host: ${{ env.DEPLOYMENT_NAME }}.play.continuouspoker.org
            image.repository: ghcr.io/${{ env.IMAGE_REPOSITORY }}
        env:
          KUBECONFIG_FILE: '${{ secrets.TOKEN }}'
