/*
 * Poker Player API
 *
 * Poker Player API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

// The player's bet.
type Bet struct {
	Bet int32 `json:"bet"`
}
