/*
 * Poker Player API
 *
 * Poker Player API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

// A playing card.
type Card struct {
	Rank *Rank `json:"rank"`

	Suit *Suit `json:"suit"`
}
