/*
 * Poker Player API
 *
 * Poker Player API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

// A player at the poker table.
type Player struct {
	// The player name.
	Name string `json:"name"`
	// The player's status. Indicates whether they are still in the game (ACTIVE), they have folded their current cards (FOLDED) or they are out of chips (OUT).
	Status string `json:"status"`
	// The player's chip stack.
	Stack int32 `json:"stack"`
	// The player's current bet.
	Bet int32 `json:"bet"`
	// The player's cards. Will only be provided for the active player, i.e. you!
	Cards []Card `json:"cards,omitempty"`
}
