/*
 * Poker Player API
 *
 * Poker Player API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

// Rank : The rank of a card.
type Rank string

// List of Rank
const (
	A     Rank = "A"
	K     Rank = "K"
	Q     Rank = "Q"
	J     Rank = "J"
	Ten   Rank = "10"
	Nine  Rank = "9"
	Eight Rank = "8"
	Seven Rank = "7"
	Six   Rank = "6"
	Five  Rank = "5"
	Four  Rank = "4"
	Three Rank = "3"
	Two   Rank = "2"
)
