/*
 * Poker Player API
 *
 * Poker Player API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

// Suit : The suit of a card.
type Suit string

// List of Suit
const (
	HEARTS   Suit = "HEARTS"
	SPADES   Suit = "SPADES"
	CLUBS    Suit = "CLUBS"
	DIAMONDS Suit = "DIAMONDS"
)
