/*
 * Poker Player API
 *
 * Poker Player API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

// The poker table, representing the current game state.
type Table struct {
	// The list of community cards on the table, visible to everyone.
	CommunityCards []Card `json:"communityCards"`
	// The list of players at the table, including you.
	Players []Player `json:"players"`
	// The number of the current round.
	Round int32 `json:"round"`
	// The current small blind of this round.
	SmallBlind int32 `json:"smallBlind"`
	// The minimum amount of chips you have to bet if you want to keep playing.
	MinimumBet int32 `json:"minimumBet"`
	// The minimum amount of chips you have to bet if you want to raise.
	MinimumRaise int32 `json:"minimumRaise"`
	// The current size of the pot of this round.
	Pot int32 `json:"pot"`
	// The index of the player whose turn it is. It's you!
	ActivePlayer int32 `json:"activePlayer"`
	// The index of the player who is the dealer of this round.
	CurrentDealer int32 `json:"currentDealer"`
}
